### ISSUE TITLE
Script not working due to initial notice page when running KR server

### ISSUE THREAD

**Issue by VoltIcaRus** [TheFunny/ArisuAutoSweeper#28]
https://github.com/TheFunny/ArisuAutoSweeper/assets/3735740/eeadcf5d-2b4d-4090-bf58-9393d5b2ee94

![image](https://github.com/TheFunny/ArisuAutoSweeper/assets/3735740/81c9ed61-1cca-439f-90c1-c1aa088d4326)

Overall, it works well, but 
There is an issue where it doesn't work if you don't close this announcement window yourself initially 

Even if the language is set to US, the server is KR, so the announcement page is always displayed on the initial launch of the game. 
I need to close this announcement and run the script, do you have any image resources you could provide? Can I take a screenshot at 720p and edit it in photoshop?

**Comment by RedDeadDepresso** [comment]
Hi, I solved the issue for the global server but I'm not sure if it's good for the korean server. You can test it by switching on the dev branch. Tactical challenge will not work since the assets have not been updated.

**Comment by VoltIcaRus** [comment]
> Hi, I solved the issue for the global server but I'm not sure if it's going to work for the korean server. You can test it by switching on the dev branch. Tactical challenge will not work since the assets have not been updated.



Ok I checked it works fine KR sever
I think it should work fine if only one store client is added, is there any way to turn off the update manually?

**Comment by RedDeadDepresso** [comment]
It is possible. You have to create a fork and add one store client on the fork's dev branch.  Then you can run gui.py and type http://127.0.0.1:23467/ on your browser to access AAS.

If you want to use the binaries, download the latest release of AAS, open config/deploy.yaml and change the Repository to your fork's url and Branch to dev.
```
Deploy:
  Git:
    # URL of AzurLaneAutoScript repository
    # [CN user] Use 'cn' to get update from self-hosted git service
    # [Other] Use 'global' to get update from https://github.com/TheFunny/ArisuAutoSweeper
    Repository: https://github.com/VoltIcaRus/ArisuAutoSweeper
    # Branch of Alas
    # [Developer] Use 'dev', 'app', etc, to try new features
    # [Other] Use 'master', the stable branch
    Branch: dev
```
